### ISSUE TITLE
Some bat files missing

### ISSUE THREAD

**Issue by chunrong** [slumdroid/slumdroid#1]
Thanks for your amazing tool! I want to have a try but I cannot find the following bat files:
FirstBoot.bat
Installer.bat;
Ripper.bat 
PostProcess.bat
close.bat

Thanks again!
Best,

**Comment by slumdroid** [comment]
Hi chunrong,

Thank you for your interest in the Slumdroid Project!!!

This is the link for Download the SlumDroid Wizard:
https://github.com/slumdroid/slumdroid/releases/tag/1.2A
[ Zip file contains the wizard, batch files and slumdroid tools...]

And this is the link of tutorial video (on Youtube):
https://www.youtube.com/watch?v=DajLhPn9p_8

If you send me a mail [ inkubo3@gmail.com ], I can send you examples  and support :)﻿
Gennaro
